### ISSUE TITLE
 ActiveDirectory module not found when already installed

### ISSUE THREAD

**Issue by bbkransomz272** [EvotecIT/PSWinDocumentation.AD#10]
Hi 

When the script starts tot test the prerequisites it comes up and says that Active Directory is not installed for some reason. 

"ActiveDirectory module not found.
[2019-12-16 15:29:53][-] ActiveDirectory module is critical for operation of this script.
[2019-12-16 15:29:53][-] Please make sure it's available on the machine before running this script
[2019-12-16 15:29:53][-] Error: The term 'Get-ADDomain' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify tha
t the path is correct and try again."

Could you please help me with this as I have already installed the XactiveDirecory

Installed Modules: 

-------    ----                                ----------           -----------
0.0.4      Connectimo                          
0.0.22     Dashimo                             
1.0.75     dbatools                            
1.1.183.57 MSOnline                            
1.0.9      PSEventViewer                   
0.0.107    PSSharedGoods                      
1.0.1      PSSlack                             
0.6        PSTeams                   
1.8.1.3    PSWinReporting                      
0.86       PSWriteColor                        
0.1.4      PSWriteExcel                   
0.0.69     PSWriteHTML                     
3.0.0.0    xActiveDirectory

**Comment by PrzemyslawKlys** [comment]
It's not xActiveDirectory. It's ActiveDirectory. ActiveDirectory is part of RSAT. You can install it using:

https://www.ntweekly.com/2017/07/04/install-all-rsat-tools-in-one-single-cmdlet-on-windows-server-2016/

For Windows 10 - google for RSAT for Windows 10.

**Comment by bbkransomz272** [comment]
Hi

I followed this link to get this installed on Windows 10 and I get the following errors:

https://www.petri.com/how-to-install-the-remote-server-administration-tools-in-windows-10



[cid:image002.png@01D5B42F.5396C4F0]

Kind Regards
Justin-Leslie
IT Administrator
Tel: 01675628720
Email: justin.leslie@kennet-leasing.co.uk
Twitter: @kennetleasing<https://twitter.com/kennetleasing>   LinkedIn: Kennet Equipment Leasing<https://www.linkedin.com/company/2252090?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2252090%2Cidx%3A2-3-11%2CtarId%3A1464873683108%2Ctas%3Akennet>

[Email Footer 04.01.18]<http://www.kennet-leasing.co.uk/>

**Comment by bbkransomz272** [comment]
If you have Windows 10 it depends which version. I believe this command is only available as part of 1809/1903/1909.

You can read: http://woshub.com/install-rsat-feature-windows-10-powershell/

For earlier version https://blogs.technet.microsoft.com/ausoemteam/2018/05/04/new-version-of-rsat-tools-available-for-download/

I really have no time to debug this for you.

With regards,
Przemek

From: Justin Leslie <justin.leslie@kennet-leasing.co.uk>
Sent: poniedziałek, 16 grudnia 2019 17:39
To: EvotecIT/PSWinDocumentation.AD <reply@reply.github.com>; Przemysław Kłys <przemyslaw.klys@evotec.pl>
Subject: RE: [EvotecIT/PSWinDocumentation.AD] ActiveDirectory module not found when already installed (#10)

Hi

I followed this link to get this installed on Windows 10 and I get the following errors:

https://www.petri.com/how-to-install-the-remote-server-administration-tools-in-windows-10



[cid:image002.png@01D5B438.280B86F0]

Kind Regards
Justin-Leslie
IT Administrator
Tel: 01675628720
Email: justin.leslie@kennet-leasing.co.uk<mailto:justin.leslie@kennet-leasing.co.uk>
Twitter: @kennetleasing<https://twitter.com/kennetleasing>   LinkedIn: Kennet Equipment Leasing<https://www.linkedin.com/company/2252090?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2252090%2Cidx%3A2-3-11%2CtarId%3A1464873683108%2Ctas%3Akennet>

[Email Footer 04.01.18]<http://www.kennet-leasing.co.uk/>
