### ISSUE TITLE
PasswordTests against pwned hashes not working

### ISSUE THREAD

**Issue by cmwg71** [EvotecIT/PSWinDocumentation.AD#11]
hello,

i installed your module PSWinDocumentation especially for the pwned statistics. I have the following in the ps1:

    PasswordTests = @{
                Use                       = $true
                # Using '' will still process some usefull output
                PasswordFilePathClearText = '' #"$PSScriptRoot\Passwords\Passwords.txt"
                # Fair warning it will take ages if you use HaveIBeenPwned DB :-)
                UseHashDB                 = $true
                PasswordFilePathHash      = 'C:\scripts\PSWinDocumentation\pwned-passwords-ntlm-ordered-by-count.txt'
            }

but the script does not aggregate the pwned hashes into statistics. It seems to be completely ignoring this part.

**Comment by PrzemyslawKlys** [comment]
It should be fixed now. At least when executed from PSWinDocumentation.AD. I'll take a look at PSWinDocumentation alone later. Tested with the newest hash DB.

Let me know how it goes.

**Comment by PrzemyslawKlys** [comment]
The recommended way would be to use - as it may be simpler.

```powershell
# Using built-in password list (just one password P@ssw0rd!)
$Passwords = Invoke-ADPasswordAnalysis
$Passwords.'ad.evotec.xyz'.DomainPasswordDuplicatePasswordGroups | Format-Table -AutoSize 'Duplicate Group', *
$Passwords.'ad.evotec.xyz' | Format-Table *

return
# Using a list of passwords
$PathToPasswords = 'C:\Support\GitHub\PSWinDocumentation.AD\Ignore\Passwords.txt'
$Passwords = Invoke-ADPasswordAnalysis -PathToPasswords $PathToPasswords
$Passwords.'ad.evotec.xyz' | Format-Table

return
# Using Hashes from IHaveBeenPwned
$PathToPasswordsHashes = 'C:\Users\przemyslaw.klys\Downloads\pwned-passwords-ntlm-ordered-by-hash-v6\pwned-passwords-ntlm-ordered-by-hash-v6.txt'
$Passwords = Invoke-ADPasswordAnalysis -PathToPasswords $PathToPasswordsHashes -UseNTLMHashes
$Passwords.'ad.evotec.xyz' | Format-Table
```
