### ISSUE TITLE
parameter cannot be found that matches parameter name 'GPOs'.

### ISSUE THREAD

**Issue by balajivisual** [EvotecIT/PSWinDocumentation.AD#14]
VERBOSE: Getting domain information - TC.LOCAL DomainGroupPoliciesACLConsistency - Time: 0 days, 0 hours, 0 minutes, 20 seconds, 474 milliseconds
VERBOSE: Getting domain information - TC.LOCAL DomainGroupPoliciesSysVol
Get-GPOZaurrBroken : A parameter cannot be found that matches parameter name 'GPOs'.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSWinDocumentation.AD\Public\Get-WinADDomainInformation.ps1:346 char:68
+ ... -GPOZaurrSysvol -Forest $Forest -IncludeDomains $Domain -GPOs $Data.D ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-GPOZaurrBroken], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-GPOZaurrBroken
 
VERBOSE: Getting domain information - TC.LOCAL DomainGroupPoliciesSysVol - Time: 0 days, 0 hours, 0 minutes, 0 seconds, 89 milliseconds

**Comment by PrzemyslawKlys** [comment]
This issue is related to change I have done in GPOZaurr - and is already reported in #13 - I need some time to fix it.
