### ISSUE TITLE
Size limit user in group

### ISSUE THREAD

**Issue by sysop200** [EvotecIT/PSWinDocumentation.AD#7]
I have more than 4000 users and an error occurs when recursively browsing groups:
------
VERBOSE: Getting domain information - MyDomainName.ru DomainGroupsMembersRecursive
WARNING: Couldn't get information about group  with SID S-1-5-21-1191908085-1747591627-2605878118-513 error: The size limit for this request was exceeded
-------
Standard cmdlets have a SizeLimit key or similar. Can you add the same to cmdlets?

P.S.
Best of the best tools... 👍 )

**Comment by PrzemyslawKlys** [comment]
I'll have to rework some of the commands. I have a big domain to support so as soon I'll get the time I hope to support really big domains. Thanks for reporting this.

**Comment by sysop200** [comment]
I myself am a system administrator and am ready to help with testing on large domains. Unfortunately, I don’t have much time for fine-tuning with a script, and I don’t want to get into your code and edit something there without your reference. I will wait for changes and will be happy to test.

**Comment by sysop200** [comment]
I solved the problem.
turned out to be looping groups among themselves
