### ISSUE TITLE
 Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sysop200** [EvotecIT/PSWinDocumentation.AD#8]
VERBOSE: Getting domain information - DomainName.ru DomainUsersFullList
Get-ADUser : Object reference not set to an instance of an object.
At C:\Program Files\WindowsPowerShell\Modules\PSWinDocumentation.AD\0.1.14\PSWinDocumentation.AD.psm1:1408 char:14
+ ...    $Users = Get-ADUser -Server $Domain -ResultPageSize $ResultPageSiz ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ADUser], NullReferenceException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.NullReferenceException,Microsoft.ActiveDirectory.Management.Commands.GetADUser

**Comment by PrzemyslawKlys** [comment]
Which command did you run with which parameters?

**Comment by sysop200** [comment]
I'm still exploring the possibilities and use your examples.
This error appeared when using the example
https://github.com/EvotecIT/PSWinDocumentation/blob/master/Examples/Run-Documentation.ActiveDirectory.ps1
The error occurred while executing the PSWinDocumentation.AD module, so I am writing to this thread.
Most likely in the section:
```powershell
SectionExcelDomainUsersFullList                   = [ordered] @{
                    Use            = $true
                    ExcelExport    = $true
                    ExcelWorkSheet = '<Domain> - Users List Full'
                    ExcelData      = [PSWinDocumentation.ActiveDirectory]::DomainUsersFullList
                }
```

**Comment by PrzemyslawKlys** [comment]
Did you modify any of the defaults from that example? I can't reproduce it.

**Comment by sysop200** [comment]
no., copy&past -> execute
This is probably due to the large catalog and somewhere there is a problem due to the large dictionary

**Comment by PrzemyslawKlys** [comment]
can you run manually `get-aduser -server 'yourdomain' -ResultPageSize 500000` because I guess that's the problem

**Comment by sysop200** [comment]
no problems.
get-aduser -server 'yourdomain' -ResultPageSize 500000 script success execute.

**Comment by PrzemyslawKlys** [comment]
```powershell
function Get-WinADDomainUsersFullList {
    [CmdletBinding()]
    param(
        [string] $Domain = $Env:USERDNSDOMAIN,
        [switch] $Extended,
        [Array] $ForestSchemaUsers,
        [HashTable] $DomainObjects,
        [int] $ResultPageSize = 500000
    )
    #Write-Verbose "Getting domain information - $Domain DomainUsersFullList"
    #$TimeUsers = Start-TimeLog
    if ($Extended) {
        [string] $Properties = '*'
    } else {
        $Properties = @(
            'Name'
            'UserPrincipalName'
            'SamAccountName'
            'DisplayName'
            'GivenName'
            'Surname'
            'EmailAddress'
            'PasswordExpired'
            'PasswordLastSet'
            'PasswordNotRequired'
            'PasswordNeverExpires'
            'Enabled'
            'Manager'
            'msDS-UserPasswordExpiryTimeComputed'
            'AccountExpirationDate'
            'AccountLockoutTime'
            'AllowReversiblePasswordEncryption'
            'BadLogonCount'
            'CannotChangePassword'
            'CanonicalName'
            'Description'
            'DistinguishedName'
            'EmployeeID'
            'EmployeeNumber'
            'LastBadPasswordAttempt'
            'LastLogonDate'
            'Created'
            'Modified'
            'ProtectedFromAccidentalDeletion'
            'PrimaryGroup'
            'MemberOf'
            if ($ForestSchemaUsers.Name -contains 'ExtensionAttribute1') {
                'ExtensionAttribute1'
                'ExtensionAttribute2'
                'ExtensionAttribute3'
                'ExtensionAttribute4'
                'ExtensionAttribute5'
                'ExtensionAttribute6'
                'ExtensionAttribute7'
                'ExtensionAttribute8'
                'ExtensionAttribute9'
                'ExtensionAttribute10'
                'ExtensionAttribute11'
                'ExtensionAttribute12'
                'ExtensionAttribute13'
                'ExtensionAttribute14'
                'ExtensionAttribute15'
            }
        )
    }

    #[string[]] $ExcludeProperty = '*Certificate', 'PropertyNames', '*Properties', 'PropertyCount', 'Certificates', 'nTSecurityDescriptor'

    $Users = Get-ADUser -Server $Domain -ResultPageSize $ResultPageSize -Filter * -Properties $Properties #| Select-Object -Property $Properties -ExcludeProperty $ExcludeProperty
    foreach ($_ in $Users) {
        #$DomainObjects.$($_.DistinguishedName) = $_
        $DomainObjects.Add($_.DistinguishedName, $_)
    }
    $Users
    #$EndUsers = Stop-TimeLog -Time $TimeUsers -Option OneLiner
    #Write-Verbose "Getting domain information - $Domain DomainUsersFullList Time: $EndUsers"
}
```
Can you execute that manually? 

Get-WinADDomainUsersFullList 

Maybe it's a problem with properties?

**Comment by sysop200** [comment]
Get-ADUser : Object reference not set to an instance of an object.
At line:69 char:14
+ ...    $Users = Get-ADUser -Server $Domain -ResultPageSize $ResultPageSiz ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ADUser], NullReferenceException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.NullReferenceException,Microsoft.ActiveDirectory.Management.Commands.GetADUser
-------------
 Error processing array 'else' in string near ")"

**Comment by sysop200** [comment]
A similar problem, so far without a solution
https://github.com/PowerShell/PowerShellModuleCoverage/issues/8

**Comment by PrzemyslawKlys** [comment]
Eh, are you using ps 6? Its not supported on ps6. It works on 5.1 and should work on 7.0 once out.

**Comment by sysop200** [comment]
I am using 5.1, just the meaning of the error that -propertie does not accept * causes an error.
I checked this and the script runs. Another error appears:

You cannot call a method on a null-valued expression.
At line:76 char:9
+         $DomainObjects.Add($_.DistinguishedName, $_)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
Forgot
At startup:
Get-WinADDomainUsersFullList
And at startup
Get-WinADDomainUsersFullList -Extended

**Comment by sysop200** [comment]
experimentally, found out that the error occurs when using the 'PrimaryGroup' attribute.

**Comment by PrzemyslawKlys** [comment]
That makes no sense to me 🤷‍♀️ why would it fail?

**Comment by sysop200** [comment]
I tested your script on a domain where 4000+ users. maybe someone will have the same problem, I suggested a solution. in my opinion the tap scripts are needed for administration, I am now writing russian documentation for my engineers to use them. Thank you so much! I will continue to study their functionality and wait for updates
